### ISSUE TITLE
IE7 suport

### ISSUE THREAD

**Issue by sebihanu** [jslegers/cascadeframeworkadvanced#7]
When I try to access the app (index.html) with IE7 I get the error "Object doesn't support this property or method". This error occurs only in IE7 and not whem try to emulate IE7 for example with IE11.

**Comment by jslegers** [comment]
Do you also get this error when using [**Cascade Framework**](http://cascade-framework.com/) or only when using **Cascade Framework Advanced**?

**Comment by jslegers** [comment]
No longer relevant
